pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t "python3-unittest:Dockerfile" -f Python3-UnitTest/Dockerfile .'
                sh 'docker images'
            }
        }
    }
}
