pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t "python3-unittest" -f Python3-UnitTest/Dockerfile .'
            }
        }
    }
}
