pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t "python3-unittest" -f Python3-UnitTest/Dockerfile .'
                sh "docker images | grep '^<none>' | awk '{print \$3}'"
                sh 'docker images'
            }
        }
    }
}
